---
Name: goldfinch-shortcode
---

# SilverStripe\ORM\FieldType\DBString:
#   extensions:
#     - App\Extensions\DBShortcode

# SilverStripe\Core\Injector\Injector:
#   HTMLVarchar:
#     properties:
#       ProcessShortcodes: true
